name: Slides - Auto Compile and Update
on:
  workflow_dispatch:
    # For manually trigger
  push:
    tags:
      - "v*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: false
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        latexmk_use_xelatex: true
    - name: Check pdf file and rename
      run: |
        file main.pdf | grep -q ' PDF '
        mv main.pdf Permissionless-Clock-Synchronization-with-Public-Setup-GKS22-Slides.pdf
    - name: Get current date
      id: date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: Slides - Permissionless Clock Synchronization with Public Setup [${{ steps.date.outputs.date }}]
        name: Slides [${{ steps.date.outputs.date }}]
        prerelease: false
        draft: false
        files: Permissionless-Clock-Synchronization-with-Public-Setup-GKS22-Slides.pdf
        token: ${{ secrets.GITHUB_TOKEN }}
